### ISSUE TITLE
Is it possible for me using link stream instead of video

### ISSUE THREAD

**Issue by phatberstromgg** [wsh122333/Multi-type_vehicles_flow_statistics#1]
Hi @wsh122333 , your project is great. I wonder if your project could you the link stream instead of video. If yes, how can I do that? Thank you.

**Comment by wsh122333** [comment]
Thanks @phatberstromgg , I use python-opencv to read the frame from video. Of cource you can easily use stream link to replace the video path in cv2.VideoCapture() function. I get the video path in line [72](https://github.com/wsh122333/Multi-type_vehicles_flow_statistics/blob/000e92dc1348485fed1dfc3eca7072638cbb4ab4/app.py#L72) of app.py and deliver to line [47](https://github.com/wsh122333/Multi-type_vehicles_flow_statistics/blob/000e92dc1348485fed1dfc3eca7072638cbb4ab4/counter.py#L47) of counter.py . You can change the video path to you own stream link in one of these two palce.

**Comment by phatberstromgg** [comment]
Thank you for your reply, I make it and it works. I wonder could you spend some time to explain the process flow of your project? I found it really great.

**Comment by wsh122333** [comment]
@phatberstromgg ,
Step 1, Using Yolov3 to detect the vehicles in frame, obtain the bboxs;
Step 2, Collecting the bboxs which are in select area, put them into SORT algorithm and can obtain the bboxs with unique ids;
Step 3, Tracking the vehicles, add the counter when they left the area.

**Comment by phatberstromgg** [comment]
Thank you. You are awesome. And do you plan to continue developing project features such as running on multiple cameras or perfecting it as a client-server system using APIs?

**Comment by wsh122333** [comment]
Thanks, May be, but not for now.
