### ISSUE TITLE
GPU doesnt working

### ISSUE THREAD

**Issue by burak-celik** [wsh122333/Multi-type_vehicles_flow_statistics#19]
Thanks a lot for your project.I installed darknet on GPU but when i run this multi type vehicle counter it uses CPU so it working slow.How can i run with GPU.Thanks for help.

**Comment by wsh122333** [comment]
This repository is independent of darknet and is fully based on pytorch. May be you can check if your pytorch supports GPU by running `python3 -c "import torch; print(torch.cuda.is_available())"` in terminal under your project's environment.

**Comment by burak-celik** [comment]
ı run python3 -c "import torch; print(torch.cuda.is_available()) this code in my virtual environment and it printed "false" what is that mean and how can i fix the problem?

**Comment by burak-celik** [comment]
i checked my torch version it is "1.8.1+cpu'

**Comment by wsh122333** [comment]
you can reinstall pytorch with cuda supports by following [pytorch officical website](https://pytorch.org/get-started/locally/).

**Comment by burak-celik** [comment]
thank you.i installed proper torch version for my cuda, now its working on gpu.
