### ISSUE TITLE
Question on vehicle counting

### ISSUE THREAD

**Issue by zahkwan04** [wsh122333/Multi-type_vehicles_flow_statistics#20]
Hi, i wanna ask,

on what line did you actually put the counting data and how do you reflect it back to the gui?

thank you

**Comment by wsh122333** [comment]
[put counting data] (https://github.com/wsh122333/Multi-type_vehicles_flow_statistics/blob/ab5b8b228bc877c6ea69cdb78b704f3e5e1e6d13/counter.py#L186)  

[reflect back to gui] (https://github.com/wsh122333/Multi-type_vehicles_flow_statistics/blob/ab5b8b228bc877c6ea69cdb78b704f3e5e1e6d13/counter.py#L194)
